name: Test fsnotify

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        nim-version:
          - binary:stable
          - nightly:https://github.com/nim-lang/nightlies/releases/tag/2024-06-25-devel-2c83f94544b9acc6d06fd6b7fcf035e5cb0aa8eb
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup nim
        uses: iffy/install-nim@v5
        with:
          version: ${{ matrix.nim-version }}

      - name: Install Packages
        run: nimble install -y

      - name: Test
        run: nimble tests
