name: Test fsnotify

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-13
        nim-version:
          - binary:stable
          - nightly:https://github.com/nim-lang/nightlies/releases/tag/latest-devel
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup nim
        uses: iffy/install-nim@v5
        with:
          version: ${{ matrix.nim-version }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Packages
        run: nimble install -y

      - name: Test
        run: nimble tests
